In [58]:
import pandas as pd

In [59]:
players = pd.read_csv('data/perfectgame/perfectgame_top50_2002-2021_raw.csv')
master = pd.read_csv('data/ncaa/school_lookup.csv')
schools = master[['school', 'school_id']]
unique_schools = schools.drop_duplicates()

In [60]:
# 982 unique schools
unique_schools

                  school  school_id
0     A&M-Corpus Christi      26172
8      Abilene Christian          2
16        Academy of Art      30123
24             Adams St.        929
32               Adelphi          3
...                  ...        ...
8004           USC Aiken      11276
8007          CSU Pueblo       2720
8115     Saint Elizabeth       9684
8364     St. Thomas (TX)       2810
8388      SUNY Brockport         78

[982 rows x 2 columns]

In [63]:
players = pd.read_csv('data/perfectgame/perfectgame_top50_2002-2021_raw.csv')

to_st = {}
for i in players.college.unique():
    if 'State' in i:
        to_st[i] = i.replace('State', 'St.') 

hardcoded_map = {'Louisiana St.':'LSU',
                 'Georgia Southern':'Ga. Southern',
                 'Miami':'Miami (FL)', 
                 'Florida International':'FIU',
                 'Mississippi':'Ole Miss',
                 'North Carolina St.':'NC State',
                 'Southern':'Southern U.',
                 'Southern Miss':'Southern Miss.',
                 'Southeastern Louisiana':'Southeastern La.',
                 'College of Charleston':'Col. of Charleston',
                 'Florida Atlantic':'Fla. Atlantic',
                 'University of Connecticut':'UConn',
                 'South Florida':'South Fla.',
                 'Dallas Baptist':'DBU',
                 'Loyola Marymount':'LMU (CA)',
                 'Brigham Young':'BYU',
                 'Illinois-Chicago':'UIC',
                 "St. John's":"St. John's (NY)",
                 'UNC-Wilmington':'UNCW'
                 }
                 # > 'Louisiana-Lafayette':}

players.college = players.college.map(to_st).fillna(players.college)
players.college = players.college.map(hardcoded_map).fillna(players.college)
master = pd.read_csv('data/ncaa/school_lookup.csv')
schools = master[['school', 'school_id']]
unique_schools = schools.drop_duplicates()
all_players = players.merge(unique_schools, how='left', left_on='college', right_on='school')

with_college = all_players[all_players.college != 'None']
no_college = all_players[all_players.college == 'None']
mapped_to_school = with_college[with_college.school_id.notna()]
not_mapped = with_college[with_college.school_id.isna()]

In [64]:
all_players

,player_name,college,rank,height,weight,bats/throws,hometown,drafted,debuted,travel_team,notes,class_year,school,school_id
0,Scott Kazmir,Texas,1,6-0,175,L/L,"Houston, TX",Rd 1 by Mets (2002),Rays (2004),ildcats,NaN,2002,Texas,703.0
1,BJ (Melvin) Upton,Florida St.,2,6-3,175,R/R,"Chesapeake, VA",Rd 1 by Rays (2002),Rays (2004),None,NaN,2002,Florida St.,234.0
2,Adam Loewen,None,3,6-6,220,L/L,"Surrey, BC",Rd 1 by Orioles (2002),Orioles (2006),None,NaN,2002,NaN,NaN
3,Christopher Gruler,Arizona St.,4,6-3,195,R/R,"Brentwood, CA",Rd 1 by Reds (2002),None,Nor Cal,NaN,2002,Arizona St.,28.0
4,Zack Greinke,Clemson,5,6-2,185,R/R,"Apopka, FL",Rd 1 by Royals (2002),Royals (2004),None,NaN,2002,Clemson,147.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,Maddux Bruns,Mississippi St.,46,6-2,210,L/L,"Saraland, AL",Rd 1 by Dodgers (2021),None,East Coast Sox,"Huge statement at the PG National, running his...",2021,Mississippi St.,430.0
996,Peyton Stovall,Arkansas,47,6-0,185,L/R,"Haughton, LA",None,None,5 Star Performance (Moran),None,2021,Arkansas,31.0
997,Maxwell Muncy,Arkansas,48,6-1,170,R/R,"Camarillo, CA",Rd 1 by Athletics (2021),None,PBA,Really impressed at 16u WWBA; high level tools...,2021,Arkansas,31.0
998,Noah Miller,Alabama,49,6-0,190,S/R,"Fredonia, WI",Rd 1 Comp by Twins (2021),None,Hitters Baseball U17,"Switch-hitter with big time offensive tools, f...",2021,Alabama,8.0
999,Pierce Coppola,Florida,50,6-8,215,L/L,"Verona, NJ",None,None,Orlando Scorpions 2021 Founder's Club,Exceptional potential at the PG National with ...,2021,Florida,235.0

In [65]:
# 933 with college
with_college

,player_name,college,rank,height,weight,bats/throws,hometown,drafted,debuted,travel_team,notes,class_year,school,school_id
0,Scott Kazmir,Texas,1,6-0,175,L/L,"Houston, TX",Rd 1 by Mets (2002),Rays (2004),ildcats,NaN,2002,Texas,703.0
1,BJ (Melvin) Upton,Florida St.,2,6-3,175,R/R,"Chesapeake, VA",Rd 1 by Rays (2002),Rays (2004),None,NaN,2002,Florida St.,234.0
3,Christopher Gruler,Arizona St.,4,6-3,195,R/R,"Brentwood, CA",Rd 1 by Reds (2002),None,Nor Cal,NaN,2002,Arizona St.,28.0
4,Zack Greinke,Clemson,5,6-2,185,R/R,"Apopka, FL",Rd 1 by Royals (2002),Royals (2004),None,NaN,2002,Clemson,147.0
5,Jason Neighborgall,Georgia Tech,6,6-5,190,R/R,"Hillsborough, NC",Rd 3 by Diamondbacks (2005),None,None,NaN,2002,Georgia Tech,255.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,Maddux Bruns,Mississippi St.,46,6-2,210,L/L,"Saraland, AL",Rd 1 by Dodgers (2021),None,East Coast Sox,"Huge statement at the PG National, running his...",2021,Mississippi St.,430.0
996,Peyton Stovall,Arkansas,47,6-0,185,L/R,"Haughton, LA",None,None,5 Star Performance (Moran),None,2021,Arkansas,31.0
997,Maxwell Muncy,Arkansas,48,6-1,170,R/R,"Camarillo, CA",Rd 1 by Athletics (2021),None,PBA,Really impressed at 16u WWBA; high level tools...,2021,Arkansas,31.0
998,Noah Miller,Alabama,49,6-0,190,S/R,"Fredonia, WI",Rd 1 Comp by Twins (2021),None,Hitters Baseball U17,"Switch-hitter with big time offensive tools, f...",2021,Alabama,8.0
999,Pierce Coppola,Florida,50,6-8,215,L/L,"Verona, NJ",None,None,Orlando Scorpions 2021 Founder's Club,Exceptional potential at the PG National with ...,2021,Florida,235.0

In [66]:
# 67 with no college
no_college

,player_name,college,rank,height,weight,bats/throws,hometown,drafted,debuted,travel_team,notes,class_year,school,school_id
2,Adam Loewen,None,3,6-6,220,L/L,"Surrey, BC",Rd 1 by Orioles (2002),Orioles (2006),None,NaN,2002,NaN,NaN
8,Denard Span,None,9,6-0,170,L/L,"Tampa, FL",Rd 1 by Twins (2002),Twins (2008),None,NaN,2002,NaN,NaN
18,Cole Hamels,None,19,6-3,170,L/L,"San Diego, CA",Rd 1 by Phillies (2002),Phillies (2006),None,NaN,2002,NaN,NaN
23,Wardell Starling,None,25,6-4,195,R/R,"Missouri City, TX",Rd 4 by Pirates (2002),None,None,NaN,2002,NaN,NaN
35,Steven Doetsch,None,38,6-2,185,R/R,"St. Petersburg, FL",Rd 8 by Phillies (2002),None,Legion,NaN,2002,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
700,Jason Groome,None,1,6-6,180,L/L,"Barnegat, NJ",Rd 1 by Red Sox (2016),None,Tri-State Arsenal,"Just a special, special arm, Easy mid 90's and...",2016,NaN,NaN
717,Delvin Perez,None,18,6-3,165,R/R,"Loiza, PR",Rd 1 by Cardinals (2016),None,IABHS Knights,Outstanding defender and very projectable hitt...,2016,NaN,NaN
740,Mario Feliciano,None,41,6-1,195,R/R,"Hato Rey, PR",Rd 2 Comp by Brewers (2016),Brewers (2021),ftb pride,Showed big time juice in his bat at PG Nationa...,2016,NaN,NaN
802,Carter Stewart,None,3,6-6,200,R/R,"Melbourne, FL",Rd 1 by Braves (2018),None,Central Florida Gators,"Very good and low 90's at WWBA, PG National an...",2018,NaN,NaN
899,Jamari Baylor,None,50,5-11,193,R/R,"Glen Allen, VA",Rd 3 by Phillies (2019),None,Virginia Cardinals,Showed big two way ability at PG National. Ma...,2019,NaN,NaN

In [67]:
# 999/1000 Successfully mapped to school 
mapped_to_school.to_csv('data/perfectgame/perfectgame_top50_2002-2021_mapped.csv')

In [68]:
# 16 not yet mapped
not_mapped

,player_name,college,rank,height,weight,bats/throws,hometown,drafted,debuted,travel_team,notes,class_year,school,school_id
210,Matthew Latos,Louisiana-Lafayette,11,6-6,200,R/R,"Margate, FL",Rd 11 by Padres (2006),Padres (2009),HS team,NaN,2006,NaN,NaN

In [53]:
# TODO: match these manually w/ baseballr::school_id_lookup
not_mapped.college.unique()

array(['Louisiana-Lafayette'], dtype=object)